module React.Icons.Bi (biAbacus, biAccessibility, biAddToQueue, biAdjust, biAlarm, biAlarmAdd, biAlarmExclamation, biAlarmOff, biAlarmSnooze, biAlbum, biAlignJustify, biAlignLeft, biAlignMiddle, biAlignRight, biAnalyse, biAnchor, biAngry, biAperture, biArch, biArchive, biArchiveIn, biArchiveOut, biArea, biArrowBack, biArrowFromBottom, biArrowFromLeft, biArrowFromRight, biArrowFromTop, biArrowToBottom, biArrowToLeft, biArrowToRight, biArrowToTop, biAt, biAtom, biAward, biBadge, biBadgeCheck, biBall, biBandAid, biBarChart, biBarChartAlt, biBarChartSquare, biBarcode, biBarcodeReader, biBaseball, biBasket, biBasketball, biBath, biBattery, biBed, biBeenHere, biBeer, biBell, biBellMinus, biBellOff, biBellPlus, biBible, biBitcoin, biBlanket, biBlock, biBluetooth, biBody, biBold, biBoltCircle, biBomb, biBone, biBong, biBook, biBookAdd, biBookAlt, biBookBookmark, biBookContent, biBookHeart, biBookmark, biBookmarkAlt, biBookmarkAltMinus, biBookmarkAltPlus, biBookmarkHeart, biBookmarkMinus, biBookmarkPlus, biBookmarks, biBookOpen, biBookReader, biBorderAll, biBorderBottom, biBorderInner, biBorderLeft, biBorderNone, biBorderOuter, biBorderRadius, biBorderRight, biBorderTop, biBot, biBowlingBall, biBox, biBracket, biBraille, biBrain, biBriefcase, biBriefcaseAlt, biBrightness, biBrightnessHalf, biBroadcast, biBrush, biBrushAlt, biBug, biBugAlt, biBuilding, biBuildingHouse, biBuildings, biBulb, biBullseye, biBuoy, biBus, biBusSchool, biCabinet, biCake, biCalculator, biCalendar, biCalendarAlt, biCalendarCheck, biCalendarEdit, biCalendarEvent, biCalendarExclamation, biCalendarHeart, biCalendarMinus, biCalendarPlus, biCalendarStar, biCalendarWeek, biCalendarX, biCamera, biCameraHome, biCameraMovie, biCameraOff, biCapsule, biCaptions, biCar, biCard, biCaretDown, biCaretDownCircle, biCaretDownSquare, biCaretLeft, biCaretLeftCircle, biCaretLeftSquare, biCaretRight, biCaretRightCircle, biCaretRightSquare, biCaretUp, biCaretUpCircle, biCaretUpSquare, biCarousel, biCart, biCartAlt, biCast, biCategory, biCategoryAlt, biCctv, biCertification, biChair, biChalkboard, biChart, biChat, biCheck, biCheckbox, biCheckboxChecked, biCheckboxMinus, biCheckboxSquare, biCheckCircle, biCheckDouble, biCheckShield, biCheckSquare, biChevronDown, biChevronDownCircle, biChevronDownSquare, biChevronLeft, biChevronLeftCircle, biChevronLeftSquare, biChevronRight, biChevronRightCircle, biChevronRightSquare, biChevronsDown, biChevronsLeft, biChevronsRight, biChevronsUp, biChevronUp, biChevronUpCircle, biChevronUpSquare, biChip, biChurch, biCircle, biClinic, biClipboard, biCloset, biCloud, biCloudDownload, biCloudDrizzle, biCloudLightning, biCloudLightRain, biCloudRain, biCloudSnow, biCloudUpload, biCode, biCodeAlt, biCodeBlock, biCodeCurly, biCoffee, biCoffeeTogo, biCog, biCoin, biCoinStack, biCollapse, biCollection, biColorFill, biColumns, biCommand, biComment, biCommentAdd, biCommentCheck, biCommentDetail, biCommentDots, biCommentEdit, biCommentError, biCommentMinus, biCommentX, biCompass, biConfused, biConversation, biCookie, biCool, biCopy, biCopyAlt, biCopyright, biCreditCard, biCreditCardAlt, biCreditCardFront, biCrop, biCrosshair, biCrown, biCube, biCubeAlt, biCuboid, biCurrentLocation, biCustomize, biCut, biCycling, biCylinder, biData, biDesktop, biDetail, biDevices, biDialpad, biDialpadAlt, biDiamond, biDirections, biDisc, biDish, biDislike, biDizzy, biDna, biDockBottom, biDockLeft, biDockRight, biDockTop, biDollar, biDollarCircle, biDonateBlood, biDonateHeart, biDoorOpen, biDotsHorizontal, biDotsHorizontalRounded, biDotsVertical, biDotsVerticalRounded, biDoughnutChart, biDownArrow, biDownArrowAlt, biDownArrowCircle, biDownload, biDownvote, biDrink, biDroplet, biDumbbell, biDuplicate, biEdit, biEditAlt, biEnvelope, biEnvelopeOpen, biEqualizer, biEraser, biError, biErrorAlt, biErrorCircle, biEuro, biExclude, biExit, biExitFullscreen, biExpand, biExpandAlt, biExport, biExtension, biFace, biFastForward, biFastForwardCircle, biFemale, biFemaleSign, biFile, biFileBlank, biFileFind, biFilm, biFilter, biFilterAlt, biFingerprint, biFirstAid, biFirstPage, biFlag, biFolder, biFolderMinus, biFolderOpen, biFolderPlus, biFont, biFontColor, biFontFamily, biFontSize, biFoodMenu, biFoodTag, biFootball, biFridge, biFullscreen, biGame, biGasPump, biGhost, biGift, biGitBranch, biGitCommit, biGitCompare, biGitMerge, biGitPullRequest, biGitRepoForked, biGlasses, biGlassesAlt, biGlobe, biGlobeAlt, biGrid, biGridAlt, biGridHorizontal, biGridSmall, biGridVertical, biGroup, biHandicap, biHappy, biHappyAlt, biHappyBeaming, biHappyHeartEyes, biHash, biHdd, biHeading, biHeadphone, biHealth, biHeart, biHeartCircle, biHeartSquare, biHelpCircle, biHide, biHighlight, biHistory, biHive, biHome, biHomeAlt, biHomeCircle, biHomeHeart, biHomeSmile, biHorizontalCenter, biHotel, biHourglass, biIdCard, biImage, biImageAdd, biImageAlt, biImages, biImport, biInfinite, biInfoCircle, biInfoSquare, biIntersect, biItalic, biJoystick, biJoystickAlt, biJoystickButton, biKey, biLabel, biLandscape, biLaptop, biLastPage, biLaugh, biLayer, biLayerMinus, biLayerPlus, biLayout, biLeftArrow, biLeftArrowAlt, biLeftArrowCircle, biLeftDownArrowCircle, biLeftIndent, biLeftTopArrowCircle, biLibrary, biLike, biLineChart, biLineChartDown, biLink, biLinkAlt, biLinkExternal, biLira, biListCheck, biListMinus, biListOl, biListPlus, biListUl, biLoader, biLoaderAlt, biLoaderCircle, biLocationPlus, biLock, biLockAlt, biLockOpen, biLockOpenAlt, biLogIn, biLogInCircle, biLogOut, biLogOutCircle, biLowVision, biMagnet, biMailSend, biMale, biMaleSign, biMap, biMapAlt, biMapPin, biMask, biMedal, biMeh, biMehAlt, biMehBlank, biMemoryCard, biMenu, biMenuAltLeft, biMenuAltRight, biMerge, biMessage, biMessageAdd, biMessageAlt, biMessageAltAdd, biMessageAltCheck, biMessageAltDetail, biMessageAltDots, biMessageAltEdit, biMessageAltError, biMessageAltMinus, biMessageAltX, biMessageCheck, biMessageDetail, biMessageDots, biMessageEdit, biMessageError, biMessageMinus, biMessageRounded, biMessageRoundedAdd, biMessageRoundedCheck, biMessageRoundedDetail, biMessageRoundedDots, biMessageRoundedEdit, biMessageRoundedError, biMessageRoundedMinus, biMessageRoundedX, biMessageSquare, biMessageSquareAdd, biMessageSquareCheck, biMessageSquareDetail, biMessageSquareDots, biMessageSquareEdit, biMessageSquareError, biMessageSquareMinus, biMessageSquareX, biMessageX, biMeteor, biMicrochip, biMicrophone, biMicrophoneOff, biMinus, biMinusBack, biMinusCircle, biMinusFront, biMobile, biMobileAlt, biMobileLandscape, biMobileVibration, biMoney, biMoon, biMouse, biMouseAlt, biMove, biMoveHorizontal, biMoveVertical, biMovie, biMoviePlay, biMusic, biNavigation, biNetworkChart, biNews, biNoEntry, biNote, biNotepad, biNotification, biNotificationOff, biOutline, biPackage, biPaint, biPaintRoll, biPalette, biPaperclip, biPaperPlane, biParagraph, biPaste, biPause, biPauseCircle, biPen, biPencil, biPhone, biPhoneCall, biPhoneIncoming, biPhoneOff, biPhoneOutgoing, biPhotoAlbum, biPieChart, biPieChartAlt, biPin, biPlanet, biPlay, biPlayCircle, biPlug, biPlus, biPlusCircle, biPlusMedical, biPodcast, biPointer, biPoll, biPolygon, biPound, biPowerOff, biPrinter, biPulse, biPurchaseTag, biPurchaseTagAlt, biPyramid, biQr, biQrScan, biQuestionMark, biRadar, biRadio, biRadioCircle, biRadioCircleMarked, biReceipt, biRectangle, biRecycle, biRedo, biRefresh, biRegistered, biRename, biRepeat, biReply, biReplyAll, biRepost, biReset, biRestaurant, biRevision, biRewind, biRewindCircle, biRightArrow, biRightArrowAlt, biRightArrowCircle, biRightDownArrowCircle, biRightIndent, biRightTopArrowCircle, biRocket, biRotateLeft, biRotateRight, biRss, biRuble, biRuler, biRun, biRupee, biSad, biSave, biScan, biScreenshot, biSearch, biSearchAlt, biSelection, biSelectMultiple, biSend, biServer, biShapeCircle, biShapePolygon, biShapeSquare, biShapeTriangle, biShare, biShareAlt, biShekel, biShield, biShieldAlt, biShieldQuarter, biShieldX, biShocked, biShoppingBag, biShow, biShowAlt, biShuffle, biSidebar, biSitemap, biSkipNext, biSkipNextCircle, biSkipPrevious, biSkipPreviousCircle, biSleepy, biSlider, biSliderAlt, biSlideshow, biSmile, biSort, biSortAZ, biSortDown, biSortUp, biSortZA, biSpa, biSpaceBar, biSpeaker, biSprayCan, biSpreadsheet, biSquare, biSquareRounded, biStar, biStation, biStats, biSticker, biStop, biStopCircle, biStopwatch, biStore, biStoreAlt, biStreetView, biStrikethrough, biSubdirectoryLeft, biSubdirectoryRight, biSun, biSupport, biSwim, biSync, biTab, biTable, biTachometer, biTag, biTagAlt, biTargetLock, biTask, biTaskX, biTaxi, biTennisBall, biTerminal, biTestTube, biText, biTime, biTimeFive, biTimer, biTired, biToggleLeft, biToggleRight, biTone, biTrafficCone, biTrain, biTransfer, biTransferAlt, biTrash, biTrashAlt, biTrendingDown, biTrendingUp, biTrim, biTrip, biTrophy, biTv, biUnderline, biUndo, biUnite, biUnlink, biUpArrow, biUpArrowAlt, biUpArrowCircle, biUpload, biUpsideDown, biUpvote, biUsb, biUser, biUserCheck, biUserCircle, biUserMinus, biUserPin, biUserPlus, biUserVoice, biUserX, biVector, biVerticalCenter, biVial, biVideo, biVideoOff, biVideoPlus, biVideoRecording, biVoicemail, biVolume, biVolumeFull, biVolumeLow, biVolumeMute, biWalk, biWallet, biWalletAlt, biWater, biWebcam, biWifi, biWifiOff, biWind, biWindow, biWindowAlt, biWindowClose, biWindowOpen, biWindows, biWine, biWinkSmile, biWinkTongue, biWon, biWorld, biWrench, biX, biXCircle, biYen, biZoomIn, biZoomOut) where

import React.Icons.Types (ReactIcon)

foreign import biAbacus :: ReactIcon
foreign import biAccessibility :: ReactIcon
foreign import biAddToQueue :: ReactIcon
foreign import biAdjust :: ReactIcon
foreign import biAlarm :: ReactIcon
foreign import biAlarmAdd :: ReactIcon
foreign import biAlarmExclamation :: ReactIcon
foreign import biAlarmOff :: ReactIcon
foreign import biAlarmSnooze :: ReactIcon
foreign import biAlbum :: ReactIcon
foreign import biAlignJustify :: ReactIcon
foreign import biAlignLeft :: ReactIcon
foreign import biAlignMiddle :: ReactIcon
foreign import biAlignRight :: ReactIcon
foreign import biAnalyse :: ReactIcon
foreign import biAnchor :: ReactIcon
foreign import biAngry :: ReactIcon
foreign import biAperture :: ReactIcon
foreign import biArch :: ReactIcon
foreign import biArchive :: ReactIcon
foreign import biArchiveIn :: ReactIcon
foreign import biArchiveOut :: ReactIcon
foreign import biArea :: ReactIcon
foreign import biArrowBack :: ReactIcon
foreign import biArrowFromBottom :: ReactIcon
foreign import biArrowFromLeft :: ReactIcon
foreign import biArrowFromRight :: ReactIcon
foreign import biArrowFromTop :: ReactIcon
foreign import biArrowToBottom :: ReactIcon
foreign import biArrowToLeft :: ReactIcon
foreign import biArrowToRight :: ReactIcon
foreign import biArrowToTop :: ReactIcon
foreign import biAt :: ReactIcon
foreign import biAtom :: ReactIcon
foreign import biAward :: ReactIcon
foreign import biBadge :: ReactIcon
foreign import biBadgeCheck :: ReactIcon
foreign import biBall :: ReactIcon
foreign import biBandAid :: ReactIcon
foreign import biBarChart :: ReactIcon
foreign import biBarChartAlt :: ReactIcon
foreign import biBarChartSquare :: ReactIcon
foreign import biBarcode :: ReactIcon
foreign import biBarcodeReader :: ReactIcon
foreign import biBaseball :: ReactIcon
foreign import biBasket :: ReactIcon
foreign import biBasketball :: ReactIcon
foreign import biBath :: ReactIcon
foreign import biBattery :: ReactIcon
foreign import biBed :: ReactIcon
foreign import biBeenHere :: ReactIcon
foreign import biBeer :: ReactIcon
foreign import biBell :: ReactIcon
foreign import biBellMinus :: ReactIcon
foreign import biBellOff :: ReactIcon
foreign import biBellPlus :: ReactIcon
foreign import biBible :: ReactIcon
foreign import biBitcoin :: ReactIcon
foreign import biBlanket :: ReactIcon
foreign import biBlock :: ReactIcon
foreign import biBluetooth :: ReactIcon
foreign import biBody :: ReactIcon
foreign import biBold :: ReactIcon
foreign import biBoltCircle :: ReactIcon
foreign import biBomb :: ReactIcon
foreign import biBone :: ReactIcon
foreign import biBong :: ReactIcon
foreign import biBook :: ReactIcon
foreign import biBookAdd :: ReactIcon
foreign import biBookAlt :: ReactIcon
foreign import biBookBookmark :: ReactIcon
foreign import biBookContent :: ReactIcon
foreign import biBookHeart :: ReactIcon
foreign import biBookmark :: ReactIcon
foreign import biBookmarkAlt :: ReactIcon
foreign import biBookmarkAltMinus :: ReactIcon
foreign import biBookmarkAltPlus :: ReactIcon
foreign import biBookmarkHeart :: ReactIcon
foreign import biBookmarkMinus :: ReactIcon
foreign import biBookmarkPlus :: ReactIcon
foreign import biBookmarks :: ReactIcon
foreign import biBookOpen :: ReactIcon
foreign import biBookReader :: ReactIcon
foreign import biBorderAll :: ReactIcon
foreign import biBorderBottom :: ReactIcon
foreign import biBorderInner :: ReactIcon
foreign import biBorderLeft :: ReactIcon
foreign import biBorderNone :: ReactIcon
foreign import biBorderOuter :: ReactIcon
foreign import biBorderRadius :: ReactIcon
foreign import biBorderRight :: ReactIcon
foreign import biBorderTop :: ReactIcon
foreign import biBot :: ReactIcon
foreign import biBowlingBall :: ReactIcon
foreign import biBox :: ReactIcon
foreign import biBracket :: ReactIcon
foreign import biBraille :: ReactIcon
foreign import biBrain :: ReactIcon
foreign import biBriefcase :: ReactIcon
foreign import biBriefcaseAlt :: ReactIcon
foreign import biBrightness :: ReactIcon
foreign import biBrightnessHalf :: ReactIcon
foreign import biBroadcast :: ReactIcon
foreign import biBrush :: ReactIcon
foreign import biBrushAlt :: ReactIcon
foreign import biBug :: ReactIcon
foreign import biBugAlt :: ReactIcon
foreign import biBuilding :: ReactIcon
foreign import biBuildingHouse :: ReactIcon
foreign import biBuildings :: ReactIcon
foreign import biBulb :: ReactIcon
foreign import biBullseye :: ReactIcon
foreign import biBuoy :: ReactIcon
foreign import biBus :: ReactIcon
foreign import biBusSchool :: ReactIcon
foreign import biCabinet :: ReactIcon
foreign import biCake :: ReactIcon
foreign import biCalculator :: ReactIcon
foreign import biCalendar :: ReactIcon
foreign import biCalendarAlt :: ReactIcon
foreign import biCalendarCheck :: ReactIcon
foreign import biCalendarEdit :: ReactIcon
foreign import biCalendarEvent :: ReactIcon
foreign import biCalendarExclamation :: ReactIcon
foreign import biCalendarHeart :: ReactIcon
foreign import biCalendarMinus :: ReactIcon
foreign import biCalendarPlus :: ReactIcon
foreign import biCalendarStar :: ReactIcon
foreign import biCalendarWeek :: ReactIcon
foreign import biCalendarX :: ReactIcon
foreign import biCamera :: ReactIcon
foreign import biCameraHome :: ReactIcon
foreign import biCameraMovie :: ReactIcon
foreign import biCameraOff :: ReactIcon
foreign import biCapsule :: ReactIcon
foreign import biCaptions :: ReactIcon
foreign import biCar :: ReactIcon
foreign import biCard :: ReactIcon
foreign import biCaretDown :: ReactIcon
foreign import biCaretDownCircle :: ReactIcon
foreign import biCaretDownSquare :: ReactIcon
foreign import biCaretLeft :: ReactIcon
foreign import biCaretLeftCircle :: ReactIcon
foreign import biCaretLeftSquare :: ReactIcon
foreign import biCaretRight :: ReactIcon
foreign import biCaretRightCircle :: ReactIcon
foreign import biCaretRightSquare :: ReactIcon
foreign import biCaretUp :: ReactIcon
foreign import biCaretUpCircle :: ReactIcon
foreign import biCaretUpSquare :: ReactIcon
foreign import biCarousel :: ReactIcon
foreign import biCart :: ReactIcon
foreign import biCartAlt :: ReactIcon
foreign import biCast :: ReactIcon
foreign import biCategory :: ReactIcon
foreign import biCategoryAlt :: ReactIcon
foreign import biCctv :: ReactIcon
foreign import biCertification :: ReactIcon
foreign import biChair :: ReactIcon
foreign import biChalkboard :: ReactIcon
foreign import biChart :: ReactIcon
foreign import biChat :: ReactIcon
foreign import biCheck :: ReactIcon
foreign import biCheckbox :: ReactIcon
foreign import biCheckboxChecked :: ReactIcon
foreign import biCheckboxMinus :: ReactIcon
foreign import biCheckboxSquare :: ReactIcon
foreign import biCheckCircle :: ReactIcon
foreign import biCheckDouble :: ReactIcon
foreign import biCheckShield :: ReactIcon
foreign import biCheckSquare :: ReactIcon
foreign import biChevronDown :: ReactIcon
foreign import biChevronDownCircle :: ReactIcon
foreign import biChevronDownSquare :: ReactIcon
foreign import biChevronLeft :: ReactIcon
foreign import biChevronLeftCircle :: ReactIcon
foreign import biChevronLeftSquare :: ReactIcon
foreign import biChevronRight :: ReactIcon
foreign import biChevronRightCircle :: ReactIcon
foreign import biChevronRightSquare :: ReactIcon
foreign import biChevronsDown :: ReactIcon
foreign import biChevronsLeft :: ReactIcon
foreign import biChevronsRight :: ReactIcon
foreign import biChevronsUp :: ReactIcon
foreign import biChevronUp :: ReactIcon
foreign import biChevronUpCircle :: ReactIcon
foreign import biChevronUpSquare :: ReactIcon
foreign import biChip :: ReactIcon
foreign import biChurch :: ReactIcon
foreign import biCircle :: ReactIcon
foreign import biClinic :: ReactIcon
foreign import biClipboard :: ReactIcon
foreign import biCloset :: ReactIcon
foreign import biCloud :: ReactIcon
foreign import biCloudDownload :: ReactIcon
foreign import biCloudDrizzle :: ReactIcon
foreign import biCloudLightning :: ReactIcon
foreign import biCloudLightRain :: ReactIcon
foreign import biCloudRain :: ReactIcon
foreign import biCloudSnow :: ReactIcon
foreign import biCloudUpload :: ReactIcon
foreign import biCode :: ReactIcon
foreign import biCodeAlt :: ReactIcon
foreign import biCodeBlock :: ReactIcon
foreign import biCodeCurly :: ReactIcon
foreign import biCoffee :: ReactIcon
foreign import biCoffeeTogo :: ReactIcon
foreign import biCog :: ReactIcon
foreign import biCoin :: ReactIcon
foreign import biCoinStack :: ReactIcon
foreign import biCollapse :: ReactIcon
foreign import biCollection :: ReactIcon
foreign import biColorFill :: ReactIcon
foreign import biColumns :: ReactIcon
foreign import biCommand :: ReactIcon
foreign import biComment :: ReactIcon
foreign import biCommentAdd :: ReactIcon
foreign import biCommentCheck :: ReactIcon
foreign import biCommentDetail :: ReactIcon
foreign import biCommentDots :: ReactIcon
foreign import biCommentEdit :: ReactIcon
foreign import biCommentError :: ReactIcon
foreign import biCommentMinus :: ReactIcon
foreign import biCommentX :: ReactIcon
foreign import biCompass :: ReactIcon
foreign import biConfused :: ReactIcon
foreign import biConversation :: ReactIcon
foreign import biCookie :: ReactIcon
foreign import biCool :: ReactIcon
foreign import biCopy :: ReactIcon
foreign import biCopyAlt :: ReactIcon
foreign import biCopyright :: ReactIcon
foreign import biCreditCard :: ReactIcon
foreign import biCreditCardAlt :: ReactIcon
foreign import biCreditCardFront :: ReactIcon
foreign import biCrop :: ReactIcon
foreign import biCrosshair :: ReactIcon
foreign import biCrown :: ReactIcon
foreign import biCube :: ReactIcon
foreign import biCubeAlt :: ReactIcon
foreign import biCuboid :: ReactIcon
foreign import biCurrentLocation :: ReactIcon
foreign import biCustomize :: ReactIcon
foreign import biCut :: ReactIcon
foreign import biCycling :: ReactIcon
foreign import biCylinder :: ReactIcon
foreign import biData :: ReactIcon
foreign import biDesktop :: ReactIcon
foreign import biDetail :: ReactIcon
foreign import biDevices :: ReactIcon
foreign import biDialpad :: ReactIcon
foreign import biDialpadAlt :: ReactIcon
foreign import biDiamond :: ReactIcon
foreign import biDirections :: ReactIcon
foreign import biDisc :: ReactIcon
foreign import biDish :: ReactIcon
foreign import biDislike :: ReactIcon
foreign import biDizzy :: ReactIcon
foreign import biDna :: ReactIcon
foreign import biDockBottom :: ReactIcon
foreign import biDockLeft :: ReactIcon
foreign import biDockRight :: ReactIcon
foreign import biDockTop :: ReactIcon
foreign import biDollar :: ReactIcon
foreign import biDollarCircle :: ReactIcon
foreign import biDonateBlood :: ReactIcon
foreign import biDonateHeart :: ReactIcon
foreign import biDoorOpen :: ReactIcon
foreign import biDotsHorizontal :: ReactIcon
foreign import biDotsHorizontalRounded :: ReactIcon
foreign import biDotsVertical :: ReactIcon
foreign import biDotsVerticalRounded :: ReactIcon
foreign import biDoughnutChart :: ReactIcon
foreign import biDownArrow :: ReactIcon
foreign import biDownArrowAlt :: ReactIcon
foreign import biDownArrowCircle :: ReactIcon
foreign import biDownload :: ReactIcon
foreign import biDownvote :: ReactIcon
foreign import biDrink :: ReactIcon
foreign import biDroplet :: ReactIcon
foreign import biDumbbell :: ReactIcon
foreign import biDuplicate :: ReactIcon
foreign import biEdit :: ReactIcon
foreign import biEditAlt :: ReactIcon
foreign import biEnvelope :: ReactIcon
foreign import biEnvelopeOpen :: ReactIcon
foreign import biEqualizer :: ReactIcon
foreign import biEraser :: ReactIcon
foreign import biError :: ReactIcon
foreign import biErrorAlt :: ReactIcon
foreign import biErrorCircle :: ReactIcon
foreign import biEuro :: ReactIcon
foreign import biExclude :: ReactIcon
foreign import biExit :: ReactIcon
foreign import biExitFullscreen :: ReactIcon
foreign import biExpand :: ReactIcon
foreign import biExpandAlt :: ReactIcon
foreign import biExport :: ReactIcon
foreign import biExtension :: ReactIcon
foreign import biFace :: ReactIcon
foreign import biFastForward :: ReactIcon
foreign import biFastForwardCircle :: ReactIcon
foreign import biFemale :: ReactIcon
foreign import biFemaleSign :: ReactIcon
foreign import biFile :: ReactIcon
foreign import biFileBlank :: ReactIcon
foreign import biFileFind :: ReactIcon
foreign import biFilm :: ReactIcon
foreign import biFilter :: ReactIcon
foreign import biFilterAlt :: ReactIcon
foreign import biFingerprint :: ReactIcon
foreign import biFirstAid :: ReactIcon
foreign import biFirstPage :: ReactIcon
foreign import biFlag :: ReactIcon
foreign import biFolder :: ReactIcon
foreign import biFolderMinus :: ReactIcon
foreign import biFolderOpen :: ReactIcon
foreign import biFolderPlus :: ReactIcon
foreign import biFont :: ReactIcon
foreign import biFontColor :: ReactIcon
foreign import biFontFamily :: ReactIcon
foreign import biFontSize :: ReactIcon
foreign import biFoodMenu :: ReactIcon
foreign import biFoodTag :: ReactIcon
foreign import biFootball :: ReactIcon
foreign import biFridge :: ReactIcon
foreign import biFullscreen :: ReactIcon
foreign import biGame :: ReactIcon
foreign import biGasPump :: ReactIcon
foreign import biGhost :: ReactIcon
foreign import biGift :: ReactIcon
foreign import biGitBranch :: ReactIcon
foreign import biGitCommit :: ReactIcon
foreign import biGitCompare :: ReactIcon
foreign import biGitMerge :: ReactIcon
foreign import biGitPullRequest :: ReactIcon
foreign import biGitRepoForked :: ReactIcon
foreign import biGlasses :: ReactIcon
foreign import biGlassesAlt :: ReactIcon
foreign import biGlobe :: ReactIcon
foreign import biGlobeAlt :: ReactIcon
foreign import biGrid :: ReactIcon
foreign import biGridAlt :: ReactIcon
foreign import biGridHorizontal :: ReactIcon
foreign import biGridSmall :: ReactIcon
foreign import biGridVertical :: ReactIcon
foreign import biGroup :: ReactIcon
foreign import biHandicap :: ReactIcon
foreign import biHappy :: ReactIcon
foreign import biHappyAlt :: ReactIcon
foreign import biHappyBeaming :: ReactIcon
foreign import biHappyHeartEyes :: ReactIcon
foreign import biHash :: ReactIcon
foreign import biHdd :: ReactIcon
foreign import biHeading :: ReactIcon
foreign import biHeadphone :: ReactIcon
foreign import biHealth :: ReactIcon
foreign import biHeart :: ReactIcon
foreign import biHeartCircle :: ReactIcon
foreign import biHeartSquare :: ReactIcon
foreign import biHelpCircle :: ReactIcon
foreign import biHide :: ReactIcon
foreign import biHighlight :: ReactIcon
foreign import biHistory :: ReactIcon
foreign import biHive :: ReactIcon
foreign import biHome :: ReactIcon
foreign import biHomeAlt :: ReactIcon
foreign import biHomeCircle :: ReactIcon
foreign import biHomeHeart :: ReactIcon
foreign import biHomeSmile :: ReactIcon
foreign import biHorizontalCenter :: ReactIcon
foreign import biHotel :: ReactIcon
foreign import biHourglass :: ReactIcon
foreign import biIdCard :: ReactIcon
foreign import biImage :: ReactIcon
foreign import biImageAdd :: ReactIcon
foreign import biImageAlt :: ReactIcon
foreign import biImages :: ReactIcon
foreign import biImport :: ReactIcon
foreign import biInfinite :: ReactIcon
foreign import biInfoCircle :: ReactIcon
foreign import biInfoSquare :: ReactIcon
foreign import biIntersect :: ReactIcon
foreign import biItalic :: ReactIcon
foreign import biJoystick :: ReactIcon
foreign import biJoystickAlt :: ReactIcon
foreign import biJoystickButton :: ReactIcon
foreign import biKey :: ReactIcon
foreign import biLabel :: ReactIcon
foreign import biLandscape :: ReactIcon
foreign import biLaptop :: ReactIcon
foreign import biLastPage :: ReactIcon
foreign import biLaugh :: ReactIcon
foreign import biLayer :: ReactIcon
foreign import biLayerMinus :: ReactIcon
foreign import biLayerPlus :: ReactIcon
foreign import biLayout :: ReactIcon
foreign import biLeftArrow :: ReactIcon
foreign import biLeftArrowAlt :: ReactIcon
foreign import biLeftArrowCircle :: ReactIcon
foreign import biLeftDownArrowCircle :: ReactIcon
foreign import biLeftIndent :: ReactIcon
foreign import biLeftTopArrowCircle :: ReactIcon
foreign import biLibrary :: ReactIcon
foreign import biLike :: ReactIcon
foreign import biLineChart :: ReactIcon
foreign import biLineChartDown :: ReactIcon
foreign import biLink :: ReactIcon
foreign import biLinkAlt :: ReactIcon
foreign import biLinkExternal :: ReactIcon
foreign import biLira :: ReactIcon
foreign import biListCheck :: ReactIcon
foreign import biListMinus :: ReactIcon
foreign import biListOl :: ReactIcon
foreign import biListPlus :: ReactIcon
foreign import biListUl :: ReactIcon
foreign import biLoader :: ReactIcon
foreign import biLoaderAlt :: ReactIcon
foreign import biLoaderCircle :: ReactIcon
foreign import biLocationPlus :: ReactIcon
foreign import biLock :: ReactIcon
foreign import biLockAlt :: ReactIcon
foreign import biLockOpen :: ReactIcon
foreign import biLockOpenAlt :: ReactIcon
foreign import biLogIn :: ReactIcon
foreign import biLogInCircle :: ReactIcon
foreign import biLogOut :: ReactIcon
foreign import biLogOutCircle :: ReactIcon
foreign import biLowVision :: ReactIcon
foreign import biMagnet :: ReactIcon
foreign import biMailSend :: ReactIcon
foreign import biMale :: ReactIcon
foreign import biMaleSign :: ReactIcon
foreign import biMap :: ReactIcon
foreign import biMapAlt :: ReactIcon
foreign import biMapPin :: ReactIcon
foreign import biMask :: ReactIcon
foreign import biMedal :: ReactIcon
foreign import biMeh :: ReactIcon
foreign import biMehAlt :: ReactIcon
foreign import biMehBlank :: ReactIcon
foreign import biMemoryCard :: ReactIcon
foreign import biMenu :: ReactIcon
foreign import biMenuAltLeft :: ReactIcon
foreign import biMenuAltRight :: ReactIcon
foreign import biMerge :: ReactIcon
foreign import biMessage :: ReactIcon
foreign import biMessageAdd :: ReactIcon
foreign import biMessageAlt :: ReactIcon
foreign import biMessageAltAdd :: ReactIcon
foreign import biMessageAltCheck :: ReactIcon
foreign import biMessageAltDetail :: ReactIcon
foreign import biMessageAltDots :: ReactIcon
foreign import biMessageAltEdit :: ReactIcon
foreign import biMessageAltError :: ReactIcon
foreign import biMessageAltMinus :: ReactIcon
foreign import biMessageAltX :: ReactIcon
foreign import biMessageCheck :: ReactIcon
foreign import biMessageDetail :: ReactIcon
foreign import biMessageDots :: ReactIcon
foreign import biMessageEdit :: ReactIcon
foreign import biMessageError :: ReactIcon
foreign import biMessageMinus :: ReactIcon
foreign import biMessageRounded :: ReactIcon
foreign import biMessageRoundedAdd :: ReactIcon
foreign import biMessageRoundedCheck :: ReactIcon
foreign import biMessageRoundedDetail :: ReactIcon
foreign import biMessageRoundedDots :: ReactIcon
foreign import biMessageRoundedEdit :: ReactIcon
foreign import biMessageRoundedError :: ReactIcon
foreign import biMessageRoundedMinus :: ReactIcon
foreign import biMessageRoundedX :: ReactIcon
foreign import biMessageSquare :: ReactIcon
foreign import biMessageSquareAdd :: ReactIcon
foreign import biMessageSquareCheck :: ReactIcon
foreign import biMessageSquareDetail :: ReactIcon
foreign import biMessageSquareDots :: ReactIcon
foreign import biMessageSquareEdit :: ReactIcon
foreign import biMessageSquareError :: ReactIcon
foreign import biMessageSquareMinus :: ReactIcon
foreign import biMessageSquareX :: ReactIcon
foreign import biMessageX :: ReactIcon
foreign import biMeteor :: ReactIcon
foreign import biMicrochip :: ReactIcon
foreign import biMicrophone :: ReactIcon
foreign import biMicrophoneOff :: ReactIcon
foreign import biMinus :: ReactIcon
foreign import biMinusBack :: ReactIcon
foreign import biMinusCircle :: ReactIcon
foreign import biMinusFront :: ReactIcon
foreign import biMobile :: ReactIcon
foreign import biMobileAlt :: ReactIcon
foreign import biMobileLandscape :: ReactIcon
foreign import biMobileVibration :: ReactIcon
foreign import biMoney :: ReactIcon
foreign import biMoon :: ReactIcon
foreign import biMouse :: ReactIcon
foreign import biMouseAlt :: ReactIcon
foreign import biMove :: ReactIcon
foreign import biMoveHorizontal :: ReactIcon
foreign import biMoveVertical :: ReactIcon
foreign import biMovie :: ReactIcon
foreign import biMoviePlay :: ReactIcon
foreign import biMusic :: ReactIcon
foreign import biNavigation :: ReactIcon
foreign import biNetworkChart :: ReactIcon
foreign import biNews :: ReactIcon
foreign import biNoEntry :: ReactIcon
foreign import biNote :: ReactIcon
foreign import biNotepad :: ReactIcon
foreign import biNotification :: ReactIcon
foreign import biNotificationOff :: ReactIcon
foreign import biOutline :: ReactIcon
foreign import biPackage :: ReactIcon
foreign import biPaint :: ReactIcon
foreign import biPaintRoll :: ReactIcon
foreign import biPalette :: ReactIcon
foreign import biPaperclip :: ReactIcon
foreign import biPaperPlane :: ReactIcon
foreign import biParagraph :: ReactIcon
foreign import biPaste :: ReactIcon
foreign import biPause :: ReactIcon
foreign import biPauseCircle :: ReactIcon
foreign import biPen :: ReactIcon
foreign import biPencil :: ReactIcon
foreign import biPhone :: ReactIcon
foreign import biPhoneCall :: ReactIcon
foreign import biPhoneIncoming :: ReactIcon
foreign import biPhoneOff :: ReactIcon
foreign import biPhoneOutgoing :: ReactIcon
foreign import biPhotoAlbum :: ReactIcon
foreign import biPieChart :: ReactIcon
foreign import biPieChartAlt :: ReactIcon
foreign import biPin :: ReactIcon
foreign import biPlanet :: ReactIcon
foreign import biPlay :: ReactIcon
foreign import biPlayCircle :: ReactIcon
foreign import biPlug :: ReactIcon
foreign import biPlus :: ReactIcon
foreign import biPlusCircle :: ReactIcon
foreign import biPlusMedical :: ReactIcon
foreign import biPodcast :: ReactIcon
foreign import biPointer :: ReactIcon
foreign import biPoll :: ReactIcon
foreign import biPolygon :: ReactIcon
foreign import biPound :: ReactIcon
foreign import biPowerOff :: ReactIcon
foreign import biPrinter :: ReactIcon
foreign import biPulse :: ReactIcon
foreign import biPurchaseTag :: ReactIcon
foreign import biPurchaseTagAlt :: ReactIcon
foreign import biPyramid :: ReactIcon
foreign import biQr :: ReactIcon
foreign import biQrScan :: ReactIcon
foreign import biQuestionMark :: ReactIcon
foreign import biRadar :: ReactIcon
foreign import biRadio :: ReactIcon
foreign import biRadioCircle :: ReactIcon
foreign import biRadioCircleMarked :: ReactIcon
foreign import biReceipt :: ReactIcon
foreign import biRectangle :: ReactIcon
foreign import biRecycle :: ReactIcon
foreign import biRedo :: ReactIcon
foreign import biRefresh :: ReactIcon
foreign import biRegistered :: ReactIcon
foreign import biRename :: ReactIcon
foreign import biRepeat :: ReactIcon
foreign import biReply :: ReactIcon
foreign import biReplyAll :: ReactIcon
foreign import biRepost :: ReactIcon
foreign import biReset :: ReactIcon
foreign import biRestaurant :: ReactIcon
foreign import biRevision :: ReactIcon
foreign import biRewind :: ReactIcon
foreign import biRewindCircle :: ReactIcon
foreign import biRightArrow :: ReactIcon
foreign import biRightArrowAlt :: ReactIcon
foreign import biRightArrowCircle :: ReactIcon
foreign import biRightDownArrowCircle :: ReactIcon
foreign import biRightIndent :: ReactIcon
foreign import biRightTopArrowCircle :: ReactIcon
foreign import biRocket :: ReactIcon
foreign import biRotateLeft :: ReactIcon
foreign import biRotateRight :: ReactIcon
foreign import biRss :: ReactIcon
foreign import biRuble :: ReactIcon
foreign import biRuler :: ReactIcon
foreign import biRun :: ReactIcon
foreign import biRupee :: ReactIcon
foreign import biSad :: ReactIcon
foreign import biSave :: ReactIcon
foreign import biScan :: ReactIcon
foreign import biScreenshot :: ReactIcon
foreign import biSearch :: ReactIcon
foreign import biSearchAlt :: ReactIcon
foreign import biSelection :: ReactIcon
foreign import biSelectMultiple :: ReactIcon
foreign import biSend :: ReactIcon
foreign import biServer :: ReactIcon
foreign import biShapeCircle :: ReactIcon
foreign import biShapePolygon :: ReactIcon
foreign import biShapeSquare :: ReactIcon
foreign import biShapeTriangle :: ReactIcon
foreign import biShare :: ReactIcon
foreign import biShareAlt :: ReactIcon
foreign import biShekel :: ReactIcon
foreign import biShield :: ReactIcon
foreign import biShieldAlt :: ReactIcon
foreign import biShieldQuarter :: ReactIcon
foreign import biShieldX :: ReactIcon
foreign import biShocked :: ReactIcon
foreign import biShoppingBag :: ReactIcon
foreign import biShow :: ReactIcon
foreign import biShowAlt :: ReactIcon
foreign import biShuffle :: ReactIcon
foreign import biSidebar :: ReactIcon
foreign import biSitemap :: ReactIcon
foreign import biSkipNext :: ReactIcon
foreign import biSkipNextCircle :: ReactIcon
foreign import biSkipPrevious :: ReactIcon
foreign import biSkipPreviousCircle :: ReactIcon
foreign import biSleepy :: ReactIcon
foreign import biSlider :: ReactIcon
foreign import biSliderAlt :: ReactIcon
foreign import biSlideshow :: ReactIcon
foreign import biSmile :: ReactIcon
foreign import biSort :: ReactIcon
foreign import biSortAZ :: ReactIcon
foreign import biSortDown :: ReactIcon
foreign import biSortUp :: ReactIcon
foreign import biSortZA :: ReactIcon
foreign import biSpa :: ReactIcon
foreign import biSpaceBar :: ReactIcon
foreign import biSpeaker :: ReactIcon
foreign import biSprayCan :: ReactIcon
foreign import biSpreadsheet :: ReactIcon
foreign import biSquare :: ReactIcon
foreign import biSquareRounded :: ReactIcon
foreign import biStar :: ReactIcon
foreign import biStation :: ReactIcon
foreign import biStats :: ReactIcon
foreign import biSticker :: ReactIcon
foreign import biStop :: ReactIcon
foreign import biStopCircle :: ReactIcon
foreign import biStopwatch :: ReactIcon
foreign import biStore :: ReactIcon
foreign import biStoreAlt :: ReactIcon
foreign import biStreetView :: ReactIcon
foreign import biStrikethrough :: ReactIcon
foreign import biSubdirectoryLeft :: ReactIcon
foreign import biSubdirectoryRight :: ReactIcon
foreign import biSun :: ReactIcon
foreign import biSupport :: ReactIcon
foreign import biSwim :: ReactIcon
foreign import biSync :: ReactIcon
foreign import biTab :: ReactIcon
foreign import biTable :: ReactIcon
foreign import biTachometer :: ReactIcon
foreign import biTag :: ReactIcon
foreign import biTagAlt :: ReactIcon
foreign import biTargetLock :: ReactIcon
foreign import biTask :: ReactIcon
foreign import biTaskX :: ReactIcon
foreign import biTaxi :: ReactIcon
foreign import biTennisBall :: ReactIcon
foreign import biTerminal :: ReactIcon
foreign import biTestTube :: ReactIcon
foreign import biText :: ReactIcon
foreign import biTime :: ReactIcon
foreign import biTimeFive :: ReactIcon
foreign import biTimer :: ReactIcon
foreign import biTired :: ReactIcon
foreign import biToggleLeft :: ReactIcon
foreign import biToggleRight :: ReactIcon
foreign import biTone :: ReactIcon
foreign import biTrafficCone :: ReactIcon
foreign import biTrain :: ReactIcon
foreign import biTransfer :: ReactIcon
foreign import biTransferAlt :: ReactIcon
foreign import biTrash :: ReactIcon
foreign import biTrashAlt :: ReactIcon
foreign import biTrendingDown :: ReactIcon
foreign import biTrendingUp :: ReactIcon
foreign import biTrim :: ReactIcon
foreign import biTrip :: ReactIcon
foreign import biTrophy :: ReactIcon
foreign import biTv :: ReactIcon
foreign import biUnderline :: ReactIcon
foreign import biUndo :: ReactIcon
foreign import biUnite :: ReactIcon
foreign import biUnlink :: ReactIcon
foreign import biUpArrow :: ReactIcon
foreign import biUpArrowAlt :: ReactIcon
foreign import biUpArrowCircle :: ReactIcon
foreign import biUpload :: ReactIcon
foreign import biUpsideDown :: ReactIcon
foreign import biUpvote :: ReactIcon
foreign import biUsb :: ReactIcon
foreign import biUser :: ReactIcon
foreign import biUserCheck :: ReactIcon
foreign import biUserCircle :: ReactIcon
foreign import biUserMinus :: ReactIcon
foreign import biUserPin :: ReactIcon
foreign import biUserPlus :: ReactIcon
foreign import biUserVoice :: ReactIcon
foreign import biUserX :: ReactIcon
foreign import biVector :: ReactIcon
foreign import biVerticalCenter :: ReactIcon
foreign import biVial :: ReactIcon
foreign import biVideo :: ReactIcon
foreign import biVideoOff :: ReactIcon
foreign import biVideoPlus :: ReactIcon
foreign import biVideoRecording :: ReactIcon
foreign import biVoicemail :: ReactIcon
foreign import biVolume :: ReactIcon
foreign import biVolumeFull :: ReactIcon
foreign import biVolumeLow :: ReactIcon
foreign import biVolumeMute :: ReactIcon
foreign import biWalk :: ReactIcon
foreign import biWallet :: ReactIcon
foreign import biWalletAlt :: ReactIcon
foreign import biWater :: ReactIcon
foreign import biWebcam :: ReactIcon
foreign import biWifi :: ReactIcon
foreign import biWifiOff :: ReactIcon
foreign import biWind :: ReactIcon
foreign import biWindow :: ReactIcon
foreign import biWindowAlt :: ReactIcon
foreign import biWindowClose :: ReactIcon
foreign import biWindowOpen :: ReactIcon
foreign import biWindows :: ReactIcon
foreign import biWine :: ReactIcon
foreign import biWinkSmile :: ReactIcon
foreign import biWinkTongue :: ReactIcon
foreign import biWon :: ReactIcon
foreign import biWorld :: ReactIcon
foreign import biWrench :: ReactIcon
foreign import biX :: ReactIcon
foreign import biXCircle :: ReactIcon
foreign import biYen :: ReactIcon
foreign import biZoomIn :: ReactIcon
foreign import biZoomOut :: ReactIcon